//
// Created by sylwia on 1/14/18.
//

#ifndef LINDACOMMUNICATION_FILEREQUESTMESSAGE_H
#define LINDACOMMUNICATION_FILEREQUESTMESSAGE_H

struct FileRequestMessage
{
    long mPrior;
};

#endif //LINDACOMMUNICATION_FILEREQUESTMESSAGE_H
